export const transactions = [
  {
    id: "#5001",
    customer: "Joseph Wheeler",
    date: "6 April, 2023",
    total: "$2,564",
    method: "CC",
    status: "Pending",
  },
  {
    id: "#5002",
    customer: "Emily Johnson",
    date: "7 April, 2023",
    total: "$1,245",
    method: "PayPal",
    status: "Completed",
  },
  {
    id: "#5003",
    customer: "Michael Brown",
    date: "8 April, 2023",
    total: "$3,678",
    method: "Bank",
    status: "Active",
  },
  {
    id: "#5004",
    customer: "Sophia Davis",
    date: "9 April, 2023",
    total: "$560",
    method: "CC",
    status: "Inactive",
  },
  {
    id: "#5005",
    customer: "James Miller",
    date: "10 April, 2023",
    total: "$4,789",
    method: "Cash",
    status: "Pending",
  },
  {
    id: "#5006",
    customer: "Olivia Wilson",
    date: "11 April, 2023",
    total: "$1,049",
    method: "PayPal",
    status: "Active",
  },
  {
    id: "#5007",
    customer: "Ethan Anderson",
    date: "12 April, 2023",
    total: "$8,652",
    method: "Bank",
    status: "Completed",
  },
  {
    id: "#5008",
    customer: "Ava Thomas",
    date: "13 April, 2023",
    total: "$2,315",
    method: "CC",
    status: "Pending",
  },
  {
    id: "#5009",
    customer: "Liam Jackson",
    date: "14 April, 2023",
    total: "$645",
    method: "Cash",
    status: "Inactive",
  },
  {
    id: "#5010",
    customer: "Mia White",
    date: "15 April, 2023",
    total: "$3,210",
    method: "Bank",
    status: "Completed",
  },
  {
    id: "#5011",
    customer: "Noah Harris",
    date: "16 April, 2023",
    total: "$9,842",
    method: "CC",
    status: "Active",
  },
  {
    id: "#5012",
    customer: "Isabella Martin",
    date: "17 April, 2023",
    total: "$1,024",
    method: "PayPal",
    status: "Pending",
  },
  {
    id: "#5013",
    customer: "William Thompson",
    date: "18 April, 2023",
    total: "$2,745",
    method: "Bank",
    status: "Completed",
  },
  {
    id: "#5014",
    customer: "Amelia Garcia",
    date: "19 April, 2023",
    total: "$5,890",
    method: "Cash",
    status: "Active",
  },
  {
    id: "#5015",
    customer: "Benjamin Martinez",
    date: "20 April, 2023",
    total: "$4,123",
    method: "PayPal",
    status: "Pending",
  },
  {
    id: "#5016",
    customer: "Charlotte Robinson",
    date: "21 April, 2023",
    total: "$6,430",
    method: "Bank",
    status: "Inactive",
  },
  {
    id: "#5017",
    customer: "Lucas Clark",
    date: "22 April, 2023",
    total: "$3,250",
    method: "CC",
    status: "Completed",
  },
  {
    id: "#5018",
    customer: "Harper Rodriguez",
    date: "23 April, 2023",
    total: "$2,910",
    method: "Cash",
    status: "Active",
  },
  {
    id: "#5019",
    customer: "Henry Lewis",
    date: "24 April, 2023",
    total: "$1,845",
    method: "PayPal",
    status: "Pending",
  },
  {
    id: "#5020",
    customer: "Evelyn Lee",
    date: "25 April, 2023",
    total: "$9,024",
    method: "Bank",
    status: "Completed",
  },
  {
    id: "#5021",
    customer: "Alexander Walker",
    date: "26 April, 2023",
    total: "$7,610",
    method: "CC",
    status: "Active",
  },
  {
    id: "#5022",
    customer: "Ella Hall",
    date: "27 April, 2023",
    total: "$2,450",
    method: "Cash",
    status: "Inactive",
  },
  {
    id: "#5023",
    customer: "Sebastian Allen",
    date: "28 April, 2023",
    total: "$4,360",
    method: "PayPal",
    status: "Pending",
  },
  {
    id: "#5024",
    customer: "Abigail Young",
    date: "29 April, 2023",
    total: "$1,975",
    method: "Bank",
    status: "Completed",
  },
  {
    id: "#5025",
    customer: "Jack Hernandez",
    date: "30 April, 2023",
    total: "$3,850",
    method: "Cash",
    status: "Pending",
  },
  {
    id: "#5026",
    customer: "Scarlett King",
    date: "1 May, 2023",
    total: "$5,960",
    method: "CC",
    status: "Active",
  },
  {
    id: "#5027",
    customer: "Daniel Wright",
    date: "2 May, 2023",
    total: "$4,123",
    method: "Bank",
    status: "Inactive",
  },
  {
    id: "#5028",
    customer: "Grace Lopez",
    date: "3 May, 2023",
    total: "$7,840",
    method: "PayPal",
    status: "Completed",
  },
  {
    id: "#5029",
    customer: "Matthew Hill",
    date: "4 May, 2023",
    total: "$9,320",
    method: "CC",
    status: "Pending",
  },
  {
    id: "#5030",
    customer: "Chloe Scott",
    date: "5 May, 2023",
    total: "$1,230",
    method: "Cash",
    status: "Active",
  },
  {
    id: "#5031",
    customer: "David Green",
    date: "6 May, 2023",
    total: "$8,910",
    method: "PayPal",
    status: "Completed",
  },
  {
    id: "#5032",
    customer: "Zoey Adams",
    date: "7 May, 2023",
    total: "$3,570",
    method: "Bank",
    status: "Inactive",
  },
  {
    id: "#5033",
    customer: "Carter Baker",
    date: "10 Oct, 2025",
    total: "$4,210",
    method: "CC",
    status: "Pending",
  },
  {
    id: "#5034",
    customer: "Layla Gonzalez",
    date: "9 Sep, 2025",
    total: "$2,870",
    method: "Cash",
    status: "Active",
  },
  {
    id: "#5035",
    customer: "Owen Nelson",
    date: "10 May, 2023",
    total: "$5,940",
    method: "PayPal",
    status: "Completed",
  },
  {
    id: "#5036",
    customer: "Luna Carter",
    date: "11 May, 2023",
    total: "$6,890",
    method: "Bank",
    status: "Inactive",
  },
  {
    id: "#5037",
    customer: "Wyatt Mitchell",
    date: "12 May, 2023",
    total: "$3,200",
    method: "Cash",
    status: "Pending",
  },
  {
    id: "#5038",
    customer: "Aria Perez",
    date: "16 Oct, 2025",
    total: "$8,560",
    method: "CC",
    status: "Completed",
  },
  {
    id: "#5039",
    customer: "Gabriel Roberts",
    date: "14 May, 2023",
    total: "$4,890",
    method: "Bank",
    status: "Active",
  },
  {
    id: "#5040",
    customer: "Ella Turner",
    date: "15 May, 2023",
    total: "$7,010",
    method: "PayPal",
    status: "Pending",
  },
  {
    id: "#5041",
    customer: "Jackson Phillips",
    date: "16 May, 2023",
    total: "$9,430",
    method: "Cash",
    status: "Inactive",
  },
  {
    id: "#5042",
    customer: "Avery Campbell",
    date: "17 May, 2023",
    total: "$3,750",
    method: "Bank",
    status: "Completed",
  },
  {
    id: "#5043",
    customer: "Levi Parker",
    date: "18 May, 2023",
    total: "$2,980",
    method: "PayPal",
    status: "Active",
  },
  {
    id: "#5044",
    customer: "Eleanor Evans",
    date: "19 May, 2023",
    total: "$5,430",
    method: "CC",
    status: "Pending",
  },
  {
    id: "#5045",
    customer: "Hudson Edwards",
    date: "20 May, 2023",
    total: "$6,720",
    method: "Cash",
    status: "Inactive",
  },
  {
    id: "#5046",
    customer: "Sofia Collins",
    date: "21 May, 2023",
    total: "$8,320",
    method: "Bank",
    status: "Completed",
  },
  {
    id: "#5047",
    customer: "Logan Stewart",
    date: "22 May, 2023",
    total: "$9,140",
    method: "PayPal",
    status: "Active",
  },
  {
    id: "#5048",
    customer: "Madison Sanchez",
    date: "23 May, 2023",
    total: "$3,230",
    method: "CC",
    status: "Pending",
  },
  {
    id: "#5049",
    customer: "Julian Morris",
    date: "24 May, 2023",
    total: "$4,870",
    method: "Cash",
    status: "Completed",
  },
  {
    id: "#5050",
    customer: "Penelope Rogers",
    date: "25 May, 2023",
    total: "$6,120",
    method: "Bank",
    status: "Active",
  },
];
